In [1]:
import numpy as np

In [2]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9],[0,1,2]])
print("Matrix\n",matrix)

Matrix
 [[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 1 2]]


In [3]:
element = matrix[1,2]
print("element at(2,3):",element)

element at(2,3): 6


In [4]:
sliced_matrix = matrix[:2,:]
print("First two rows\n",sliced_matrix)

First two rows
 [[1 2 3]
 [4 5 6]]
